INSERT INTO delegacias (cidade_busca, cidade_exibicao, endereco) VALUES
('abreu e lima', 'Abreu e Lima', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('afogados da ingazeira', 'Afogados da Ingazeira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('afranio', 'Afrânio', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('agrestina', 'Agrestina', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('agua preta', 'Água Preta', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('aguas belas', 'Águas Belas', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('alagoinha', 'Alagoinha', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('alianca', 'Aliança', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('altinho', 'Altinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('amaraji', 'Amaraji', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('angelim', 'Angelim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('aracoiaba', 'Araçoiaba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('araripina', 'Araripina', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('arcoverde', 'Arcoverde', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('barra de guabiraba', 'Barra de Guabiraba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('barreiros', 'Barreiros', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('belem de maria', 'Belém de Maria', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('belem do sao francisco', 'Belém do São Francisco', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('belo jardim', 'Belo Jardim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('betania', 'Betânia', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('bezerros', 'Bezerros', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('bodoco', 'Bodocó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('bom conselho', 'Bom Conselho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('bom jardim', 'Bom Jardim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('bonito', 'Bonito', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('brejao', 'Brejão', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('brejinho', 'Brejinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('brejo da madre de deus', 'Brejo da Madre de Deus', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('buenos aires', 'Buenos Aires', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('buique', 'Buíque', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cabo de santo agostinho', 'Cabo de Santo Agostinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cabrobo', 'Cabrobó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cachoeirinha', 'Cachoeirinha', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('caetes', 'Caetés', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('calcado', 'Calçado', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('calumbi', 'Calumbi', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('camaragibe', 'Camaragibe', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('camocim de sao felix', 'Camocim de São Félix', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('camutanga', 'Camutanga', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('canhotinho', 'Canhotinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('capoeiras', 'Capoeiras', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('carnaiba', 'Carnaíba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('carnaubeira da penha', 'Carnaubeira da Penha', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('carpina', 'Carpina', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('caruaru', 'Caruaru', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('casinhas', 'Casinhas', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('catende', 'Catende', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cedro', 'Cedro', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cha de alegria', 'Chã de Alegria', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cha grande', 'Chã Grande', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('condado', 'Condado', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('correntes', 'Correntes', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cortes', 'Cortês', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cumaru', 'Cumaru', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('cupira', 'Cupira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('custodia', 'Custódia', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('dormentes', 'Dormentes', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('escada', 'Escada', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('exu', 'Exu', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('feira nova', 'Feira Nova', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ferreiros', 'Ferreiros', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('flores', 'Flores', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('floresta', 'Floresta', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('frei miguelinho', 'Frei Miguelinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('gameleira', 'Gameleira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('garanhuns', 'Garanhuns', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('gloria do goita', 'Glória do Goitá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('goiana', 'Goiana', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('granito', 'Granito', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('gravata', 'Gravatá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('iati', 'Iati', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ibimirim', 'Ibimirim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ibirajuba', 'Ibirajuba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('igarassu', 'Igarassu', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('iguaracy', 'Iguaracy', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('inaja', 'Inajá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ingazeira', 'Ingazeira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ipojuca', 'Ipojuca', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ipubi', 'Ipubi', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itacuruba', 'Itacuruba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itaiba', 'Itaíba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ilha de itamaraca', 'Ilha de Itamaracá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itambe', 'Itambé', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itapetim', 'Itapetim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itapissuma', 'Itapissuma', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('itaquitinga', 'Itaquitinga', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jaboatao dos guararapes', 'Jaboatão dos Guararapes', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jaqueira', 'Jaqueira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jatauba', 'Jataúba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jatoba', 'Jatobá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('joao alfredo', 'João Alfredo', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('joaquim nabuco', 'Joaquim Nabuco', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jucati', 'Jucati', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jupi', 'Jupi', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('jurema', 'Jurema', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lagoa do carro', 'Lagoa do Carro', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lagoa de itaenga', 'Lagoa de Itaenga', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lagoa do ouro', 'Lagoa do Ouro', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lagoa dos gatos', 'Lagoa dos Gatos', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lagoa grande', 'Lagoa Grande', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('lajedo', 'Lajedo', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('limoeiro', 'Limoeiro', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('macaparana', 'Macaparana', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('machados', 'Machados', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('manari', 'Manari', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('maraial', 'Maraial', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('mirandiba', 'Mirandiba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('moreno', 'Moreno', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('nazare da mata', 'Nazaré da Mata', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('olinda', 'Olinda', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('orobo', 'Orobó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('oroco', 'Orocó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ouricuri', 'Ouricuri', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('palmares', 'Palmares', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('palmeirina', 'Palmeirina', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('panelas', 'Panelas', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('paranatama', 'Paranatama', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('parnamirim', 'Parnamirim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('passira', 'Passira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('paudalho', 'Paudalho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('paulista', 'Paulista', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('pedra', 'Pedra', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('pesqueira', 'Pesqueira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('petrolandia', 'Petrolândia', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('petrolina', 'Petrolina', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('pocao', 'Poção', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('pombos', 'Pombos', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('primavera', 'Primavera', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('quipapa', 'Quipapá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('quixaba', 'Quixaba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('recife', 'Recife', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('riacho das almas', 'Riacho das Almas', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('ribeirao', 'Ribeirão', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('rio formoso', 'Rio Formoso', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('saire', 'Sairé', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('salgadinho', 'Salgadinho', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('salgueiro', 'Salgueiro', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('saloa', 'Saloá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sanharo', 'Sanharó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa cruz', 'Santa Cruz', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa cruz da baixa verde', 'Santa Cruz da Baixa Verde', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa cruz do capibaribe', 'Santa Cruz do Capibaribe', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa filomena', 'Santa Filomena', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa maria da boa vista', 'Santa Maria da Boa Vista', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa maria do cambuca', 'Santa Maria do Cambucá', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('santa terezinha', 'Santa Terezinha', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao benedito do sul', 'São Benedito do Sul', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao bento do una', 'São Bento do Una', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao caitano', 'São Caitano', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao joao', 'São João', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao joaquim do monte', 'São Joaquim do Monte', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao jose da coroa grande', 'São José da Coroa Grande', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao jose do belmonte', 'São José do Belmonte', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao jose do egito', 'São José do Egito', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao lourenco da mata', 'São Lourenço da Mata', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sao vicente ferrer', 'São Vicente Férrer', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('serra talhada', 'Serra Talhada', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('serrita', 'Serrita', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sertania', 'Sertânia', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('sirinhaem', 'Sirinhaém', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('moreilandia', 'Moreilândia', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('solidao', 'Solidão', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('surubim', 'Surubim', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tabira', 'Tabira', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tacaimbo', 'Tacaimbó', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tacaratu', 'Tacaratu', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tamandare', 'Tamandaré', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('taquaritinga do norte', 'Taquaritinga do Norte', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('terezinha', 'Terezinha', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('terra nova', 'Terra Nova', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('timbauba', 'Timbaúba', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('toritama', 'Toritama', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tracunhaem', 'Tracunhaém', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('trindade', 'Trindade', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('triunfo', 'Triunfo', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tupanatinga', 'Tupanatinga', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('tuparetama', 'Tuparetama', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('venturosa', 'Venturosa', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('verdejante', 'Verdejante', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('vertente do lerio', 'Vertente do Lério', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('vertentes', 'Vertentes', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('vicencia', 'Vicência', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('vitoria de santo antao', 'Vitória de Santo Antão', 'Endereço em atualização. Verifique no site oficial da PCPE.'),
('xexeu', 'Xexéu', 'Endereço em atualização. Verifique no site oficial da PCPE.');